module.exports.Users = require('./users/users.service')
module.exports.Sessions = require('./sessions/sessions.service')
module.exports.Games = require('./games/games.service')
module.exports.Codes = require('./codes/codes.service')
module.exports.SendGrid = require('./sendgrid')